apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:

      # ------------------------------
      # 1) DB migrate 먼저 실행 (initContainer)
      # ------------------------------
      initContainers:
        - name: migrate
          image: hpark8672/django-app:1.2
          command: ["sh", "-c", "python manage.py migrate"]
          envFrom:
            - secretRef:
                name: db-secret
            - configMapRef:
                name: django-config

      # ------------------------------
      # 2) Django 메인 앱 컨테이너
      # ------------------------------
      containers:
        - name: mysite
          image: hpark8672/django-app:1.2
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: db-secret
            - configMapRef:
                name: django-config
          command: ["gunicorn"]
          args: ["config.wsgi:application", "--bind", "0.0.0.0:8000"]
